services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZONE}
    depends_on:
      - jellyfin
    networks:
      - ${MY_NET}
    ports:
      - ${SONARR_HOST_PORT}:${SONARR_CONTAINER_PORT}
    volumes:
      - .\config:/config
      - ${MEDIA_DIR}:/media
      #- path\to\downloads:/downloads #optional
    restart: unless-stopped
    labels: 
      - homepage.group=Media
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=http://${HOST}:${SONARR_HOST_PORT}
      - homepage.description=TV series management
      - homepage.ping=http://${HOST}:${SONARR_HOST_PORT}
      - homepage.showStats=false
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://sonarr:${SONARR_HOST_PORT}
      - homepage.widget.key=${SONARR_API_KEY}
      - homepage.widget.enableQueue=true