services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZONE}
    volumes:
      - .\config:/config
      - .\img:/app/public/images
    networks:
      - Media_server_net
    ports:
      - ${HEIMDALL_HTTP_HOST_PORT}:${HEIMDALL_HTTP_CONTAINER_PORT}
      - ${HEIMDALL_HTTPS_HOST_PORT}:${HEIMDALL_HTTPS_CONTAINER_PORT} # optional https port
    restart: unless-stopped