services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZONE} #optional
      - DB_CONNECTION=${SPEEDTEST_DB}
      - APP_KEY=${SPEEDTEST_TRACKER_APPKEY}
      - SPEEDTEST_SCHEDULE=${SPEEDTEST_SCHEDULE} #optional (cron expression)
      - PRUNE_RESULTS_OLDER_THAN=${SPEEDTEST_PRUNE} #optional (value in days)
      #- DB_HOST= #optional
      #- DB_PORT= #optional
      #- DB_DATABASE= #optional
      #- DB_USERNAME= #optional
      #- DB_PASSWORD= #optional
    depends_on:
      - swag
    networks:
      - Media_server_net
    ports:
      - ${SPEEDTEST_HOST_PORT}:${SPEEDTEST_CONTAINER_PORT}
    volumes:
      - .\config:/config
      #- /path/to-custom-ssl-keys:/config/keys
    restart: unless-stopped
    labels:
      - homepage.group=Network
      - homepage.name=Speedtest tracker
      - homepage.icon=si-speedtest
      - homepage.href=http://${HOST}:${SPEEDTEST_CONTAINER_PORT}
      - homepage.description=Speedtest monitor
      - homepage.ping=http://${HOST}:${SPEEDTEST_CONTAINER_PORT}
      - homepage.showStats=false
      - homepage.widget.type=speedtest
      - homepage.widget.url=http://speedtest-tracker:${SPEEDTEST_CONTAINER_PORT}