services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZONE}
      - VIRTUAL_HOST=${DUCKDNS_SUBDOMAIN}.duckdns.org
      #- VIRTUAL_PORT=<<port>> #optional. Tell nginx which port to proxy if the container exposes multiple ports. Remember to also edit the corresponding nginx .conf files accordingly.
    depends_on:
      - prowlarr
    networks:
      - Media_server_net
    ports:
      #- ${RADARR_HTTP_HOST_PORT}:${RADARR_HTTP_CONTAINER_PORT} # Default HTTP port. In-app manual settings required to enable SSL. You can comment out this line after setting up SSL. 
      - ${RADARR_HTTPS_HOST_PORT}:${RADARR_HTTPS_CONTAINER_PORT} 
    volumes:
      - .\config:/config
      - ..\swag\config\etc:/swag-ssl
      - ${MEDIA_DIR}:/data
    restart: unless-stopped
    labels: 
      - homepage.group=Media
      - homepage.name=Radarr
      - homepage.icon=radarr.png
      - homepage.description=Movie management
      - homepage.showStats=false
      - homepage.href=https://${DUCKDNS_SUBDOMAIN}.duckdns.org/radarr # Replace this value with http://localhost:${RADARR_HTTP_HOST_PORT} in order to test the widget before setting up SSL.
      - homepage.ping=https://${DUCKDNS_SUBDOMAIN}.duckdns.org/radarr # Replace this value with http://localhost:${RADARR_HTTP_HOST_PORT} in order to test the widget before setting up SSL.
      - homepage.widget.type=radarr
      - homepage.widget.url=https://radarr:${RADARR_HTTPS_HOST_PORT} # Replace this value with http://radarr:${RADARR_HTTP_HOST_PORT} in order to test the widget before setting up SSL.
      - homepage.widget.key=${RADARR_API_KEY}
      - homepage.widget.enableQueue=true
