services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZONE}
      - VIRTUAL_HOST=${DUCKDNS_SUBDOMAIN}.duckdns.org
      #- VIRTUAL_PORT=${JELLYFIN_HTTPS_HOST_PORT} #optional. Tell nginx which port to proxy if the container exposes multiple ports. Remember to also edit the corresponding nginx .conf files accordingly.
      #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    depends_on:
      - swag
    networks:
      - Media_server_net
    ports:
      - ${JELLYFIN_HTTP_HOST_PORT}:${JELLYFIN_HTTP_CONTAINER_PORT}
      - ${JELLYFIN_HTTPS_HOST_PORT}:${JELLYFIN_HTTPS_CONTAINER_PORT} #optional https port
      #- ${JELLYFIN_UDP_HTTP_HOST_PORT}:${JELLYFIN_UDP_HTTP_CONTAINER_PORT}/udp #optional
      #- ${JELLYFIN_UDP_HTTPS_HOST_PORT}:${JELLYFIN_UDP_HTTPS_CONTAINER_PORT}/udp #optional
    volumes:
      - .\config:/config
      - ..\swag\config\etc:/swag-ssl
      - ${MEDIA_DIR}:/data/media/
    restart: unless-stopped
    labels: 
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin.png
      - homepage.description=Media server
      - homepage.showStats=false
      - homepage.href=http://${HOST}:${JELLYFIN_HTTP_HOST_PORT}
      - homepage.ping=http://${HOST}:${JELLYFIN_HTTP_HOST_PORT}
      - homepage.widget.type=jellyfin
      - homepage.widget.url=http://jellyfin:${JELLYFIN_HTTP_HOST_PORT}
      - homepage.widget.key=${JELLYFIN_API_KEY}
      - homepage.widget.enableBlocks=true
