services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZONE}
      #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    depends_on:
      - dockerproxy
    networks:
      - ${MY_NET}
    ports:
      - ${JELLYFIN_HTTP_HOST_PORT}:${JELLYFIN_HTTP_CONTAINER_PORT}
      #- ${JELLYFIN_HTTPS_HOST_PORT}:${JELLYFIN_HTTPS_CONTAINER_PORT} #optional https port
      #- ${JELLYFIN_UDP_HTTP_HOST_PORT}:${JELLYFIN_UDP_HTTP_CONTAINER_PORT}/udp #optional
      #- ${JELLYFIN_UDP_HTTPS_HOST_PORT}:${JELLYFIN_UDP_HTTPS_CONTAINER_PORT}/udp #optional
    volumes:
      - .\config:/config
      - F:\:/media
      #- path\to\tvseries:/tv #optional
      #- path\to\downloads:/downloads #optional
    restart: unless-stopped
    labels: 
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin.png
      - homepage.href=http://${HOST}:${JELLYFIN_HTTP_HOST_PORT}
      - homepage.description=Media server
      - homepage.ping=http://${HOST}:${JELLYFIN_HTTP_HOST_PORT}
      - homepage.showStats=false
      - homepage.widget.type=jellyfin
      - homepage.widget.url=http://jellyfin:${JELLYFIN_HTTP_HOST_PORT}
      - homepage.widget.key=${JELLYFIN_API_KEY}
      - homepage.widget.enableBlocks=true