services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZONE}
    depends_on:
      - jellyfin
    networks:
      - ${MY_NET}
    ports:
      - ${LIDARR_HOST_PORT}:${LIDARR_CONTAINER_PORT}
    volumes:
      - .\config:/config
      - ${DATA_DIR}:/data
      #- path\to\downloads:/downloads #optional
    restart: unless-stopped
    labels: 
      - homepage.group=Media
      - homepage.name=Lidarr
      - homepage.icon=lidarr.png
      - homepage.href=http://${HOST}:${LIDARR_HOST_PORT}
      - homepage.description=Music management
      - homepage.ping=http://${HOST}:${LIDARR_HOST_PORT}
      - homepage.showStats=false
      - homepage.widget.type=lidarr
      - homepage.widget.url=http://lidarr:${LIDARR_HOST_PORT}
      - homepage.widget.key=${LIDARR_API_KEY}
