services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZONE}
      - VIRTUAL_HOST=${DUCKDNS_SUBDOMAIN}.duckdns.org
      #- VIRTUAL_PORT=<<port>> #optional. Tell nginx which port to proxy if the container exposes multiple ports. Remember to also edit the corresponding nginx .conf files accordingly.
    depends_on:
      - prowlarr
    networks:
      - Media_server_net
    ports:
      #- ${LIDARR_HTTP_HOST_PORT}:${LIDARR_HTTP_CONTAINER_PORT} # Default HTTP port. In-app manual settings required to enable SSL. You can comment out this line after setting up SSL. 
      - ${LIDARR_HTTPS_HOST_PORT}:${LIDARR_HTTPS_CONTAINER_PORT}
    volumes:
      - .\config:/config
      - ..\swag\config\etc:/swag-ssl
      - ${MEDIA_DIR}:/data
    restart: unless-stopped
    labels: 
      - homepage.group=Media
      - homepage.name=Lidarr
      - homepage.icon=lidarr.png
      - homepage.description=Music management
      - homepage.showStats=false
      - homepage.href=https://${DUCKDNS_SUBDOMAIN}.duckdns.org/lidarr # Replace this value with http://localhost:${LIDARR_HTTP_HOST_PORT} in order to test the widget before setting up SSL. If using the awful workaround explained in swag.yaml file, replace the value with https://${DUCKDNS_SUBDOMAIN}.duckdns.org/lidarr
      - homepage.ping=https://${DUCKDNS_SUBDOMAIN}.duckdns.org/lidarr # Replace this value with http://localhost:${LIDARR_HTTP_HOST_PORT} in order to test the widget before setting up SSL. If using the awful workaround explained in swag.yaml file, replace the value with https://${DUCKDNS_SUBDOMAIN}.duckdns.org/lidarr
      - homepage.widget.type=lidarr
      - homepage.widget.url=https://lidarr:${LIDARR_HTTPS_CONTAINER_PORT} # Replace this value with http://lidarr:${LIDARR_HTTP_CONTAINER_PORT} in order to test the widget before setting up SSL.
      - homepage.widget.key=${LIDARR_API_KEY}
