services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZONE}
    networks:
      - ${MY_NET}
    ports:
      - ${NPM_HTTP_HOST_PORT}:${NPM_HTTP_CONTAINER_PORT}
      - ${NPM_HTTPS_HOST_PORT}:${NPM_HTTPS_CONTAINER_PORT} # https port
      - ${NPM_ADMIN_HOST_PORT}:${NPM_ADMIN_CONTAINER_PORT} # adminUI port
    volumes:
      - .\data:/data
      - .\letsencrypt:/etc/letsencrypt    
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    labels: 
      - homepage.group=Network
      - homepage.name=Nginx proxy manager
      - homepage.icon=nginx-proxy-manager.png
      - homepage.href=http://${HOST}:${NPM_ADMIN_HOST_PORT}
      - homepage.description=Reverse proxy
      - homepage.ping=http://${HOST}:${NPM_ADMIN_HOST_PORT}
      - homepage.showStats=false
      - homepage.widget.type=npm
      - homepage.widget.url=http://npm:${NPM_ADMIN_HOST_PORT}
      - homepage.widget.username=${NPM_ADMIN_USER}
      - homepage.widget.password=${NPM_ADMIN_PWD}